[package]
name = "raknet-rs"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["iGxnon"]
resolver = "2"

[dependencies]
bytes = "1.4.0"
derive_builder = "0.13.0"
flume = "0.11"
futures = "0.3.28"
futures-async-stream = "0.2"
log = "0.4"
lru = "0.12.0"
minitrace = { version = "0.6" }
minstant = "0.1"
pin-project-lite = "0.2.10"
priority-queue = "1.3.2"
rand = { version = "0.8", optional = true }
thiserror = "1.0.49"
tokio = { version = "1.29.1", features = ["io-util", "macros"] }
tokio-util = { version = "0.7.9", features = ["codec", "net", "io-util"] }

[dev-dependencies]
criterion = { version = "0.5", features = ["async_futures"] }
env_logger = "0.11.1"
minitrace = { version = "0.6", features = ["enable"] }
rand = "0.8"

[features]
micro-bench = ["dep:rand"]

[[bench]]
name = "codec"
harness = false

[profile.bench]
opt-level = 3
lto = true
