[package]
name = "raknet-rs"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["iGxnon"]
resolver = "2"

[dependencies]
bytes = "1.4.0"
derive_builder = "0.12.0"
flume = "0.11"
futures = "0.3.28"
futures-async-stream = "0.2"
lru = "0.12.0"
pin-project-lite = "0.2.10"
priority-queue = "1.3.2"
thiserror = "1.0.49"
tokio = { version = "1.29.1", features = ["io-util", "macros"] }
tokio-util = { version = "0.7.9", features = ["codec", "net", "io-util"] }
tracing = "0.1.37"
rand = { version = "0.8", optional = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["async_futures"] }
indexmap = "2.1.0"
rand = "0.8"
tracing-test = { version = "0.2.4", features = ["no-env-filter"] }

[features]
micro-bench = ["dep:rand"]

[[bench]]
name = "codec"
harness = false
