[package]
name = "raknet-rs"
version = "0.1.1"
edition = "2021"
license = "Apache-2.0"
authors = ["iGxnon"]
resolver = "2"
description = "Raknet protocol implementation by rust"
homepage = "https://github.com/MemoriesOfTime/raknet-rs"
repository = "https://github.com/MemoriesOfTime/raknet-rs"
readme = "README.md"
categories = ["network-programming"]
keywords = ["raknet", "network", "udp"]

[dependencies]
bytes = "1"
derive_builder = "0.20"
flume = "0.11"
futures = "0.3"
futures-async-stream = "0.2"
log = "0.4"
lru = "0.12"
minitrace = { version = "0.6" }
minstant = "0.1"
pin-project-lite = "0.2"
priority-queue = "2.0"
rand = { version = "0.8", optional = true }
thiserror = "1"
tokio = { version = "1", features = ["io-util", "macros"], optional = true }
tokio-util = { version = "0.7", features = [
    "codec",
    "net",
    "io-util",
], optional = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["async_futures", "async_tokio"] }
env_logger = "0.11"
indexmap = "2"
minitrace = { version = "0.6", features = ["enable"] }
rand = "0.8"
reqwest = "0.12"
tokio = { version = "1", features = ["full"] }

[features]
default = ["tokio-udp"]
micro-bench = ["dep:rand"]
tokio-udp = ["dep:tokio-util", "dep:tokio"]

[[bench]]
name = "micro"
harness = false
required-features = ["micro-bench"]
# Not available currently
# [[bench]]
# name = "bulk"
# harness = false

[profile.bench]
opt-level = 3
lto = true
