[package]
name = "raknet-rs"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["iGxnon"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
futures = "0.3.28"
lru = "0.12.0"
pin-project-lite = "0.2.10"
priority-queue = "1.3.2"
thiserror = "1.0.49"
tokio = { version = "1.29.1", features = ["io-util", "macros"] }
tokio-util = { version = "0.7.9", features = ["codec", "net", "io-util"] }
tracing = "0.1.37"

[dev-dependencies]
tracing-test = { version = "0.2.4", features = ["no-env-filter"] }
