# codecov config
# Reference: https://docs.codecov.com/docs/codecovyml-reference
# Tips. You may run following command to validate before committing any changes
#   curl --data-binary @codecov.yml https://codecov.io/validate
coverage:
  status:
    patch: off # disable patch status
    project:
      default: false  # disable the default status that measures entire project
      rust:
        paths:
          - "src/"
        target: auto # compared with the coverage from the base commit
        threshold: 0.1% # allow the coverage to drop by 0.1% and posting a success status
codecov:
  allow_coverage_offsets: true
