# codecov config
# Reference: https://docs.codecov.com/docs/codecovyml-reference
# Tips. You may run following command to validate before committing any changes
#   curl --data-binary @codecov.yml https://codecov.io/validate
coverage:
  range: "70..95"
  precision: 2
  round: down
  status:
    patch:
      default:
        informational: true
    project:
      default:
        target: auto
        threshold: "1%" # allow drop by 1%
    changes:
      default:
        informational: true
codecov:
  allow_coverage_offsets: true
