name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTC_WRAPPER: sccache

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@cargo-binstall

      - name: Install Deps
        run: |
          rustup component add rustfmt llvm-tools-preview clippy
          cargo binstall -y --no-symlinks cargo-llvm-cov cargo-nextest cargo-sort cargo-audit
          wget https://github.com/mozilla/sccache/releases/download/v0.7.5/sccache-v0.7.5-x86_64-unknown-linux-musl.tar.gz
          mkdir sccache-install && tar -xzf sccache-v0.7.5-x86_64-unknown-linux-musl.tar.gz -C sccache-install --strip-components=1
          mv sccache-install/sccache /usr/local/bin && rm -rf sccache-install/

      - name: Test
        run: ci/scripts/run-ci-test.sh
